### ISSUE TITLE
Suggestion: Add url link when click the notification

### ISSUE THREAD

**Issue by ghost** [dgknca/simple-notify#25]
it would be great if add this feature. Since in this version, the notify only serve for notice something, if add onclick function and go to certain link, I believe it would be more powerful.

**Comment by dgknca** [comment]
This is a good idea. We can conditionally create `a` element instead of `div` at [L#140](https://github.com/dgknca/simple-notify/blob/master/src/ts/index.ts#L140)

We need an option something like:

```js
new Notify({
  ...
  link: {
    href: 'https://github.com/dgknca/simple-notify',
    target: '_blank'
    // and much more, we should spread all of the object properties as `attribute="value"` pairs.
  }
})
```
the `link` property should be `undefined` or `null` by default (not sure). If user uses the `link`, `a` should be used instead of `div`.

Would you like to work on this?

**Comment by NicolasBiondini** [comment]
i'm goin to work on that if you let me!

**Comment by alpercun** [comment]
Hey @dgknca! Can you assign this to me?
